name: ifelse saple
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codes
        uses: actions/checkout@v2

      - name: echo hello
        id: echo_hello
        run:  echo "hello"

      - name: echo event
        id: echo_event
        run:  echo ${{github.event_name}}

      - name: echo ref
        run:  echo ${{github.ref}}

      - name: echo repository url
        run:  echo ${{github.repositoryUrl}}

      - name: always true
        if: true
        run:  echo "TRUE"

      - name: always false
        if: false
        run:  echo "FALSE"

      - name: tagging only step
        if: startsWith(github.ref, 'refs/tags/')
        run:  echo tagging only step

      - name: Get the version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Get commit summary
        id: get_commit_summary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n 2p)
          echo "PREVIOUS_TAG: $PREVIOUS_TAG"
          COMMIT_SUMMARY="$(git log --oneline --pretty=tformat:"%h %s" $PREVIOUS_TAG..${{ github.ref }})"
          COMMIT_SUMMARY="${COMMIT_SUMMARY//$'\n'/'%0A'}"
          echo ::set-output name=COMMIT_SUMMARY::$COMMIT_SUMMARY

      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ${{ steps.get_commit_summary.outputs.COMMIT_SUMMARY }}
          draft: true
          prerelease: false
