name: ifelse saple
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codes
        uses: actions/checkout@v2

      - name: echo hello
        id: echo_hello
        run:  echo "hello"

      - name: echo event
        id: echo_event
        run:  echo ${{github.event_name}}

      - name: echo ref
        run:  echo ${{github.ref}}

      - name: echo repository url
        run:  echo ${{github.repositoryUrl}}

      - name: always true
        if: true
        run:  echo "TRUE"

      - name: always false
        if: false
        run:  echo "FALSE"

      - name: tagging only step
        if: startsWith(github.ref, 'refs/tags/')
        run:  echo tagging only step

